name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Deploy to server1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/flask_app/PythonBoard
            git pull origin main
            sudo systemctl restart gunicorn_app
      - name: Deploy to server2
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SERVER_HOST2 }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY2 }}
            script: |
              cd /home/ubuntu/flask_app/PythonBoard
              git pull origin main
              sudo systemctl restart gunicorn_app
    